Repository DEFRA/cyltfr-app, pull requests merged in 2024-12, with the labels that each got.

#80 Quick fixes following testing
  client/sass/_map-controls.scss
  client/sass/map-page.scss
  server/src/js/map-page/constants.js
  server/src/js/map-page/map-page.js
  server/views/map.html
Labels: bug, enhancement

#82 Quick fix to minor map issues
  server/src/js/map-page/map-page.js
Labels: bug

#85 No result appearing for climate change R&S flooding and current extent
  server/models/risk-view.js
  server/views/partials/rivers-sea.html
  server/views/partials/surface-water.html
Labels: bug

#86 Amend colour of very low tag on more about R&S page
  client/sass/_rivers-and-sea.scss
  server/models/risk-view.js
  server/views/partials/rivers-sea.html
  server/views/partials/surface-water.html
  server/views/rivers-and-sea.html
Labels: bug

#91 Update map definitions for Production data
  README.MD
  server/models/definition/P01/maps.json
Labels: enhancement

#90 All risks on depth pages appear blue in colour
  server/models/__tests__/depth-view.spec.js
  server/models/depth-view.js
Labels: bug

#77 Tech debt: Increase CYLTF App unit test coverage
  server/__tests__/cache.spec.js
  server/__tests__/util-perf.spec.js
  server/__tests__/util.spec.js
  server/models/__tests__/depth-view.spec.js
  server/plugins/__tests__/airbrake-schema.spec.js
  server/routes/__tests__/ground-water.spec.js
  server/routes/__tests__/map.spec.js
  server/routes/__tests__/os-get-token.spec.js
  server/routes/__tests__/rivers-and-sea-depth.spec.js
  server/routes/__tests__/rivers-and-sea.spec.js
  server/routes/__tests__/surface-water-depth.spec.js
  server/routes/__tests__/surface-water.spec.js
  server/server-methods/__tests__/server-methods-disabled-cache.spec.js
  server/server-methods/__tests__/server-methods-enabled-cache.spec.js
  server/services/__tests__/address.spec.js
  server/services/__tests__/defineBackLink.spec.js
  server/services/__tests__/flood.spec.js
Labels: enhancement

#87 Revert print option in internet browsers back to default settings
  client/sass/_risk-page.scss
  server/routes/__tests__/risk.spec.js
  server/views/risk.html
Labels: enhancement

#93 Bypass Blocks Issue - Summary pages
  server/views/ground-water.html
  server/views/rivers-and-sea.html
  server/views/surface-water.html
Labels: enhancement

#92 Page Titles Issue (All pages)
  server/routes/feedback.js
  server/views/map-reservoirs.html
  server/views/map-rivers-and-sea.html
  server/views/map-surface-water.html
  server/views/os-terms.html
  server/views/risk.html
  server/views/rivers-and-sea-depth.html
Labels: enhancement

#94 Redundant entry (postcode and address pages)
  server/routes/__tests__/postcode.spec.js
  server/routes/postcode.js
Labels: enhancement

#95 Headings hierarchy (Rivers and sea and surface water depth)
  server/routes/__tests__/privacy-notice.spec.js
  server/views/map-rivers-and-sea.html
  server/views/map-surface-water.html
  server/views/map.html
  server/views/partials/rs-depth-gauge-20.html
  server/views/partials/rs-depth-gauge-30.html
  server/views/partials/rs-depth-gauge-60.html
  server/views/partials/sw-depth-gauge-20.html
  server/views/partials/sw-depth-gauge-30.html
  server/views/partials/sw-depth-gauge-60.html
  server/views/privacy-notice.html
Labels: enhancement
