Repository DEFRA/cyltfr-app, pull requests merged in 2025-01, with the labels that each got.

#97 Page Titles Issue (All pages) - Technical Map Update
  server/views/map.html
Labels: enhancement

#98 Change On Request 01 (Where do you want to check)
  server/views/postcode.html
Labels: enhancement

#99 Phase Banner Usability (Where do you want to check)
  server/views/layout.html
Labels: enhancement

#102 Update accessibility statement to incorporate changes post DAC audit
  server/views/accessibility-statement.html
Labels: enhancement

#96 Focus order (Map pages)
  client/sass/_map-controls.scss
  client/sass/map-page.scss
  package-lock.json
  package.json
  server/src/js/map-page/map-page.js
  server/views/map-reservoirs.html
  server/views/map-rivers-and-sea.html
  server/views/map-surface-water.html
  server/views/map.html
  server/views/partials/map-page/key/toggles.html
  server/views/partials/map-page/map-controls.html
Labels: enhancement

#104 Update README files, Licence definitions and CONTRIBUTING files
  README.MD
  package-lock.json
  package.json
Labels: documentation

#106 Update map reservoir tiles URL
  server/models/definition/03/maps.json
Labels: bug

#108 Accessibility statement fix
  server/views/accessibility-statement.html
Labels: bug

#109 Remove "Selected address" checkbox from r&s and reservoirs key on tec…
  server/src/js/map-page/constants.js
  server/src/js/map-page/map-page.js
  server/views/partials/map-page/key/toggles.html
Labels: bug

#110 Show flooding toggle not working on technical map
  server/src/js/map-page/map-page.js
  server/views/partials/map-page/key/toggles.html
Labels: bug

#107 Add back button to pages they're missing on
  server/routes/accessibility-statement.js
  server/routes/cookies.js
  server/routes/os-terms.js
  server/routes/postcode.js
  server/routes/privacy-notice.js
  server/routes/risk.js
  server/routes/search.js
  server/routes/surface-water-depth.js
  server/routes/terms-and-conditions.js
  server/services/defineBackLink.js
  server/views/accessibility-statement.html
  server/views/cookies.html
  server/views/os-terms.html
  server/views/privacy-notice.html
  server/views/terms-and-conditions.html
Labels: enhancement

#113 Additional Changes - interrupter page before a user enters the techni…
  server/views/information-for-planning.html
Labels: enhancement

#117 create back button on feedback survey
  server/routes/feedback.js
  server/services/defineBackLink.js
  server/views/feedback.html
Labels: enhancement

#125 Upgrade workflow actions to use latest components
  .github/workflows/unittests.yml
Labels: enhancement

#126 Change receive flood warning text to match CFF/NWS content
  server/views/rivers-and-sea.html
Labels: enhancement

#121 Add focus state styling to map and map buttons
  client/sass/_map-controls.scss
  client/sass/map-page.scss
  server/src/js/map-page/map-page.js
Labels: enhancement

#123 Info and Relationships 02 (Rivers and Seas Depth)
  server/views/partials/rs-depth-gauge-20.html
  server/views/partials/rs-depth-gauge-30.html
  server/views/partials/rs-depth-gauge-60.html
  server/views/partials/sw-depth-gauge-20.html
  server/views/partials/sw-depth-gauge-30.html
  server/views/partials/sw-depth-gauge-60.html
Labels: enhancement

#130 Headings and labels (Rivers and Sea details)
  server/views/ground-water.html
  server/views/rivers-and-sea.html
  server/views/surface-water.html
Labels: enhancement

#131 Change On Request 02 (Rivers and Sea map)
  server/src/js/map-page/map-page.js
Labels: enhancement

#127 Section Headings (Rivers and Sea details)
  server/views/ground-water.html
  server/views/rivers-and-sea.html
  server/views/surface-water.html
Labels: enhancement

#132 Contrast Minimum
  server/views/postcode.html
Labels: enhancement

#133 Additional changes - Info and Relationships 02 (Rivers and Seas Depth)
  server/views/partials/rs-depth-gauge-20.html
  server/views/partials/rs-depth-gauge-30.html
  server/views/partials/rs-depth-gauge-60.html
  server/views/partials/sw-depth-gauge-20.html
  server/views/partials/sw-depth-gauge-30.html
  server/views/partials/sw-depth-gauge-60.html
Labels: enhancement

#138 /os-get-token route is filling logs
  server/routes/__tests__/os-get-token.spec.js
  server/routes/os-get-token.js
  server/services/__mocks__/osapi.js
  server/src/js/map.js
Labels: enhancement

#137 Quick fix to close button
  server/src/js/map-page/map-page.js
Labels: bug

#140 Depth pages on mobile
  client/sass/_depth-gauges.scss
Labels: enhancement
